In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from graph_tool.all import *
import numpy as np

In [3]:
X = bin(20)[2:]
X_array = np.asarray(list(X)).astype(int)

In [4]:
weights = abs(np.random.randn(5))
weights = weights/sum(weights)

In [16]:
from Memory import get_binary_codes, initialize_memory

In [28]:
weights

array([0.05536679, 0.2724255 , 0.11387378, 0.34761789, 0.21071604])

In [21]:
get_binary_codes(5, 8)

array([[0, 1, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 0, 1, 0, 0],
       [0, 1, 1, 1, 0, 0, 1, 0],
       [1, 0, 0, 0, 1, 0, 0, 0]])

In [125]:
memory = initialize_memory()

In [58]:
len(np.unique(memory[0], axis = 1))

50

In [161]:
np.random.uniform(size = 5)

array([0.60111501, 0.70807258, 0.02058449, 0.96990985, 0.83244264])

In [157]:
np.apply_along_axis(f, 0, a[0])

array([2, 3, 2, 3, 2])

In [138]:
a, b = np.unique(memory[0], axis = 0, return_counts = True)

In [168]:
a[0]

array([0, 1, 0, 1, 0])

In [185]:
a[0][np.argwhere(a[0]).reshape(-1)]

array([1, 1])

In [186]:
a[0]

array([1, 0, 0, 1, 0])

In [188]:
np.logical_not(a[0]).astype(int)

array([0, 1, 1, 0, 1])

In [144]:
list(np.apply_along_axis(binary_to_string, 1, a))

['01010',
 '01011',
 '01100',
 '01101',
 '01110',
 '01111',
 '10000',
 '10001',
 '10010',
 '10011',
 '10100',
 '10101']

In [77]:
list(zip(a, b))

[(array([0, 1, 0, 0, 1]), 1),
 (array([0, 1, 0, 1, 1]), 2),
 (array([0, 1, 1, 0, 0]), 1),
 (array([0, 1, 1, 0, 1]), 5),
 (array([0, 1, 1, 1, 0]), 9),
 (array([0, 1, 1, 1, 1]), 8),
 (array([1, 0, 0, 0, 0]), 6),
 (array([1, 0, 0, 0, 1]), 2),
 (array([1, 0, 0, 1, 0]), 5),
 (array([1, 0, 0, 1, 1]), 3),
 (array([1, 0, 1, 0, 0]), 5),
 (array([1, 0, 1, 0, 1]), 2),
 (array([1, 0, 1, 1, 0]), 1)]

In [87]:
np.array2string(memory[0][0])

'[0 1 1 1 1]'

In [88]:
code = memory[0][0]

'01111'

In [86]:
[str(code) for code in np.unique(memory[0], axis = 0)]

['[0 1 0 0 1]',
 '[0 1 0 1 1]',
 '[0 1 1 0 0]',
 '[0 1 1 0 1]',
 '[0 1 1 1 0]',
 '[0 1 1 1 1]',
 '[1 0 0 0 0]',
 '[1 0 0 0 1]',
 '[1 0 0 1 0]',
 '[1 0 0 1 1]',
 '[1 0 1 0 0]',
 '[1 0 1 0 1]',
 '[1 0 1 1 0]']

In [72]:
memory[0][0] == np.asarray([0, 1, 1, 1, 1])

array([ True,  True,  True,  True,  True])

In [121]:
from Memory import generate_code, binary_to_string
code_length = 5

In [102]:
{binary_to_string(generate_code(x, code_length)):0 for x in range(2**code_length)} 

{'00000': 0,
 '00001': 0,
 '00010': 0,
 '00011': 0,
 '00100': 0,
 '00101': 0,
 '00110': 0,
 '00111': 0,
 '01000': 0,
 '01001': 0,
 '01010': 0,
 '01011': 0,
 '01100': 0,
 '01101': 0,
 '01110': 0,
 '01111': 0,
 '10000': 0,
 '10001': 0,
 '10010': 0,
 '10011': 0,
 '10100': 0,
 '10101': 0,
 '10110': 0,
 '10111': 0,
 '11000': 0,
 '11001': 0,
 '11010': 0,
 '11011': 0,
 '11100': 0,
 '11101': 0,
 '11110': 0,
 '11111': 0}

In [126]:
from Memory import probability_distribution, random_selection

In [130]:
P = probability_distribution(memory)
P

{'00000': 0,
 '00001': 0,
 '00010': 0,
 '00011': 0,
 '00100': 0,
 '00101': 0,
 '00110': 0,
 '00111': 0,
 '01000': 0,
 '01001': 0,
 '01010': 0.02,
 '01011': 0.04,
 '01100': 0.06,
 '01101': 0.16,
 '01110': 0.1,
 '01111': 0.1,
 '10000': 0.16,
 '10001': 0.14,
 '10010': 0.08,
 '10011': 0.04,
 '10100': 0.02,
 '10101': 0.08,
 '10110': 0,
 '10111': 0,
 '11000': 0,
 '11001': 0,
 '11010': 0,
 '11011': 0,
 '11100': 0,
 '11101': 0,
 '11110': 0,
 '11111': 0}

In [131]:
sum(P.values())

1.0

In [137]:
random_selection(P)

array([1, 0, 1, 0, 1])

In [192]:
price_network(1000, gamma = 1, directed = False)

<Graph object, undirected, with 1000 vertices and 999 edges, at 0x7f305da01e80>

In [194]:
price_network(20000)

<Graph object, directed, with 20000 vertices and 19999 edges, at 0x7f305da01be0>